export const COLD_DEPLOYMENT_SLO_OBJECTIVE_SECONDS = 300 as const;
export const COLD_DEPLOYMENT_SLO_OBJECTIVE_MS = COLD_DEPLOYMENT_SLO_OBJECTIVE_SECONDS * 1_000;
export const COLD_DEPLOYMENT_SLO_SAMPLE_SIZE = 100 as const;
export const COLD_DEPLOYMENT_SLO_READY_REQUIRED = 95 as const;
