ALTER TABLE "agent_secrets" ADD COLUMN "uniqueness_fingerprint" text;--> statement-breakpoint
ALTER TABLE "agent_secrets" ADD COLUMN "provider_subject_id" text;--> statement-breakpoint
ALTER TABLE "agent_secrets" ADD COLUMN "provider_username" text;--> statement-breakpoint
CREATE UNIQUE INDEX "agent_secrets_active_telegram_uniqueness_idx" ON "agent_secrets" USING btree ("uniqueness_fingerprint") WHERE "agent_secrets"."kind" = 'telegram_bot_token' AND "agent_secrets"."status" = 'active' AND "agent_secrets"."uniqueness_fingerprint" IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "agent_secrets_active_telegram_subject_idx" ON "agent_secrets" USING btree ("provider_subject_id") WHERE "agent_secrets"."kind" = 'telegram_bot_token' AND "agent_secrets"."status" = 'active' AND "agent_secrets"."provider_subject_id" IS NOT NULL;--> statement-breakpoint
ALTER TABLE "agent_secrets" ADD CONSTRAINT "agent_secrets_uniqueness_fingerprint_check" CHECK ("agent_secrets"."uniqueness_fingerprint" IS NULL OR "agent_secrets"."uniqueness_fingerprint" ~ '^[0-9a-f]{64}$');--> statement-breakpoint
ALTER TABLE "agent_secrets" ADD CONSTRAINT "agent_secrets_provider_subject_id_check" CHECK ("agent_secrets"."provider_subject_id" IS NULL OR "agent_secrets"."provider_subject_id" ~ '^[1-9][0-9]{0,19}$');--> statement-breakpoint
ALTER TABLE "agent_secrets" ADD CONSTRAINT "agent_secrets_provider_username_check" CHECK ("agent_secrets"."provider_username" IS NULL OR "agent_secrets"."provider_username" ~ '^[A-Za-z][A-Za-z0-9_]{4,31}$');--> statement-breakpoint
ALTER TABLE "agent_secrets" ADD CONSTRAINT "agent_secrets_telegram_metadata_kind_check" CHECK ("agent_secrets"."kind" = 'telegram_bot_token' OR ("agent_secrets"."uniqueness_fingerprint" IS NULL AND "agent_secrets"."provider_subject_id" IS NULL AND "agent_secrets"."provider_username" IS NULL));--> statement-breakpoint
ALTER TABLE "agent_secrets" ADD CONSTRAINT "agent_secrets_telegram_metadata_pair_check" CHECK ("agent_secrets"."kind" <> 'telegram_bot_token' OR ("agent_secrets"."uniqueness_fingerprint" IS NULL AND "agent_secrets"."provider_subject_id" IS NULL AND "agent_secrets"."provider_username" IS NULL) OR ("agent_secrets"."uniqueness_fingerprint" IS NOT NULL AND "agent_secrets"."provider_subject_id" IS NOT NULL));