ALTER TABLE "founder_recovery_archive_deletion_receipts" RENAME COLUMN "provider_confirmed" TO "archive_provider_confirmed";--> statement-breakpoint
ALTER TABLE "founder_product_entitlements" DROP CONSTRAINT "founder_product_entitlements_retirement_due_check";--> statement-breakpoint
ALTER TABLE "founder_recovery_archive_deletion_receipts" DROP CONSTRAINT "founder_recovery_archive_deletions_outcome_check";--> statement-breakpoint
ALTER TABLE "founder_recovery_archives" DROP CONSTRAINT "founder_recovery_archives_outcome_check";--> statement-breakpoint
ALTER TABLE "founder_recovery_archive_deletion_receipts" ADD COLUMN "recovery_credentials_confirmed" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "founder_recovery_archives" ADD COLUMN "recovery_credential_digest" text;--> statement-breakpoint
ALTER TABLE "founder_product_entitlements" ADD CONSTRAINT "founder_product_entitlements_retirement_due_check" CHECK (("founder_product_entitlements"."status" = 'verified' AND "founder_product_entitlements"."retirement_due_at" IS NULL) OR ("founder_product_entitlements"."status" IN ('past_due', 'unpaid', 'cancelled', 'expired', 'refunded') AND "founder_product_entitlements"."retirement_due_at" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "founder_recovery_archive_deletion_receipts" ADD CONSTRAINT "founder_recovery_archive_deletions_outcome_check" CHECK (("founder_recovery_archive_deletion_receipts"."status" = 'pending' AND "founder_recovery_archive_deletion_receipts"."archive_provider_confirmed" = false AND "founder_recovery_archive_deletion_receipts"."recovery_credentials_confirmed" = false AND "founder_recovery_archive_deletion_receipts"."completed_at" IS NULL) OR ("founder_recovery_archive_deletion_receipts"."status" = 'completed' AND "founder_recovery_archive_deletion_receipts"."archive_provider_confirmed" = true AND "founder_recovery_archive_deletion_receipts"."recovery_credentials_confirmed" = true AND "founder_recovery_archive_deletion_receipts"."completed_at" IS NOT NULL AND "founder_recovery_archive_deletion_receipts"."failure_code" IS NULL));--> statement-breakpoint
ALTER TABLE "founder_recovery_archives" ADD CONSTRAINT "founder_recovery_archives_credential_digest_check" CHECK ("founder_recovery_archives"."recovery_credential_digest" IS NULL OR "founder_recovery_archives"."recovery_credential_digest" ~ '^sha256:[a-f0-9]{64}$');--> statement-breakpoint
ALTER TABLE "founder_recovery_archives" ADD CONSTRAINT "founder_recovery_archives_outcome_check" CHECK (("founder_recovery_archives"."status" = 'pending' AND "founder_recovery_archives"."storage_object_key" IS NULL AND "founder_recovery_archives"."ciphertext_digest" IS NULL AND "founder_recovery_archives"."recovery_credential_digest" IS NULL AND "founder_recovery_archives"."restorable_verified" = false AND "founder_recovery_archives"."failure_code" IS NULL AND "founder_recovery_archives"."deleted_at" IS NULL) OR ("founder_recovery_archives"."status" = 'verified' AND "founder_recovery_archives"."storage_object_key" IS NOT NULL AND "founder_recovery_archives"."ciphertext_digest" IS NOT NULL AND "founder_recovery_archives"."recovery_credential_digest" IS NOT NULL AND "founder_recovery_archives"."restorable_verified" = true AND "founder_recovery_archives"."failure_code" IS NULL AND "founder_recovery_archives"."deleted_at" IS NULL) OR ("founder_recovery_archives"."status" = 'failed' AND "founder_recovery_archives"."recovery_credential_digest" IS NULL AND "founder_recovery_archives"."restorable_verified" = false AND "founder_recovery_archives"."failure_code" IS NOT NULL AND "founder_recovery_archives"."deleted_at" IS NULL) OR ("founder_recovery_archives"."status" = 'deleted' AND "founder_recovery_archives"."storage_object_key" IS NULL AND "founder_recovery_archives"."recovery_credential_digest" IS NULL AND "founder_recovery_archives"."restorable_verified" = false AND "founder_recovery_archives"."failure_code" IS NULL AND "founder_recovery_archives"."deleted_at" IS NOT NULL));