ALTER TABLE "founder_checkout_correlations" DROP CONSTRAINT "founder_checkout_correlations_status_check";--> statement-breakpoint
ALTER TABLE "founder_checkout_correlations" DROP CONSTRAINT "founder_checkout_correlations_consumed_check";--> statement-breakpoint
ALTER TABLE "founder_checkout_correlations" ADD COLUMN "provider_checkout_id" text;--> statement-breakpoint
ALTER TABLE "founder_checkout_correlations" ADD COLUMN "provider_subscription_id" text;--> statement-breakpoint
ALTER TABLE "founder_checkout_correlations" ADD COLUMN "provider_order_id" text;--> statement-breakpoint
ALTER TABLE "founder_checkout_correlations" ADD COLUMN "payment_detected_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "founder_checkout_correlations" ADD COLUMN "reconciliation_due_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "founder_checkout_correlations" ADD COLUMN "refund_requested_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "founder_checkout_correlations" ADD COLUMN "refund_lease_token" uuid;--> statement-breakpoint
ALTER TABLE "founder_checkout_correlations" ADD COLUMN "refund_lease_expires_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "founder_checkout_correlations" ADD COLUMN "refund_attempt_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "founder_checkout_correlations" ADD COLUMN "refund_last_error_code" text;--> statement-breakpoint
ALTER TABLE "founder_checkout_correlations" ADD COLUMN "refunded_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "founder_checkout_correlations" ADD COLUMN "closed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "founder_checkout_correlations" ADD COLUMN "closure_reason" text;--> statement-breakpoint
ALTER TABLE "founder_commerce_events" ADD COLUMN "provider_order_id" text;--> statement-breakpoint
ALTER TABLE "founder_commerce_events" ADD COLUMN "application_status" text DEFAULT 'pending' NOT NULL;--> statement-breakpoint
ALTER TABLE "founder_commerce_events" ADD COLUMN "last_attempt_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "founder_commerce_events" ADD COLUMN "applied_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "founder_commerce_events" ADD COLUMN "last_error_code" text;--> statement-breakpoint
ALTER TABLE "founder_product_entitlements" ADD COLUMN "provider_state_updated_at" timestamp with time zone;--> statement-breakpoint
UPDATE "founder_commerce_events" SET "provider_order_id" = 'legacy-order-' || "provider_subscription_id", "application_status" = 'applied', "last_attempt_at" = "recorded_at", "applied_at" = "recorded_at";--> statement-breakpoint
UPDATE "founder_product_entitlements" AS entitlement SET "provider_state_updated_at" = coalesce((SELECT event."occurred_at" FROM "founder_commerce_events" AS event WHERE event."id" = entitlement."source_event_id"), entitlement."reconciled_at");--> statement-breakpoint
ALTER TABLE "founder_commerce_events" ALTER COLUMN "provider_order_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "founder_product_entitlements" ALTER COLUMN "provider_state_updated_at" SET NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "founder_checkout_correlations_subscription_idx" ON "founder_checkout_correlations" USING btree ("provider_subscription_id");--> statement-breakpoint
CREATE UNIQUE INDEX "founder_checkout_correlations_order_idx" ON "founder_checkout_correlations" USING btree ("provider_order_id");--> statement-breakpoint
CREATE INDEX "founder_checkout_correlations_reconciliation_due_idx" ON "founder_checkout_correlations" USING btree ("status","reconciliation_due_at");--> statement-breakpoint
ALTER TABLE "founder_checkout_correlations" ADD CONSTRAINT "founder_checkout_correlations_payment_check" CHECK (("founder_checkout_correlations"."payment_detected_at" IS NULL AND "founder_checkout_correlations"."reconciliation_due_at" IS NULL AND "founder_checkout_correlations"."provider_subscription_id" IS NULL AND "founder_checkout_correlations"."provider_order_id" IS NULL) OR ("founder_checkout_correlations"."payment_detected_at" IS NOT NULL AND "founder_checkout_correlations"."reconciliation_due_at" = "founder_checkout_correlations"."payment_detected_at" + interval '1 hour' AND "founder_checkout_correlations"."provider_subscription_id" IS NOT NULL AND "founder_checkout_correlations"."provider_order_id" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "founder_checkout_correlations" ADD CONSTRAINT "founder_checkout_correlations_refund_check" CHECK (("founder_checkout_correlations"."refund_requested_at" IS NULL AND "founder_checkout_correlations"."refund_lease_token" IS NULL AND "founder_checkout_correlations"."refund_lease_expires_at" IS NULL AND "founder_checkout_correlations"."refunded_at" IS NULL AND "founder_checkout_correlations"."refund_attempt_count" = 0) OR ("founder_checkout_correlations"."refund_requested_at" IS NOT NULL AND "founder_checkout_correlations"."refund_attempt_count" > 0 AND ("founder_checkout_correlations"."refunded_at" IS NULL OR "founder_checkout_correlations"."refunded_at" >= "founder_checkout_correlations"."refund_requested_at")));--> statement-breakpoint
ALTER TABLE "founder_checkout_correlations" ADD CONSTRAINT "founder_checkout_correlations_refund_lease_check" CHECK (("founder_checkout_correlations"."refund_lease_token" IS NULL AND "founder_checkout_correlations"."refund_lease_expires_at" IS NULL) OR ("founder_checkout_correlations"."status" = 'refund_pending' AND "founder_checkout_correlations"."refund_lease_token" IS NOT NULL AND "founder_checkout_correlations"."refund_lease_expires_at" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "founder_checkout_correlations" ADD CONSTRAINT "founder_checkout_correlations_closed_check" CHECK ("founder_checkout_correlations"."status" <> 'closed' OR ("founder_checkout_correlations"."closure_reason" = 'payment_without_access_refunded' AND "founder_checkout_correlations"."refunded_at" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "founder_checkout_correlations" ADD CONSTRAINT "founder_checkout_correlations_status_check" CHECK ("founder_checkout_correlations"."status" IN ('pending', 'consumed', 'refund_pending', 'closed'));--> statement-breakpoint
ALTER TABLE "founder_checkout_correlations" ADD CONSTRAINT "founder_checkout_correlations_consumed_check" CHECK (("founder_checkout_correlations"."status" = 'pending' AND "founder_checkout_correlations"."consumed_at" IS NULL AND "founder_checkout_correlations"."closed_at" IS NULL AND "founder_checkout_correlations"."closure_reason" IS NULL) OR ("founder_checkout_correlations"."status" IN ('consumed', 'refund_pending') AND "founder_checkout_correlations"."consumed_at" IS NOT NULL AND "founder_checkout_correlations"."closed_at" IS NULL AND "founder_checkout_correlations"."closure_reason" IS NULL) OR ("founder_checkout_correlations"."status" = 'closed' AND "founder_checkout_correlations"."consumed_at" IS NOT NULL AND "founder_checkout_correlations"."closed_at" IS NOT NULL AND "founder_checkout_correlations"."closure_reason" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "founder_commerce_events" ADD CONSTRAINT "founder_commerce_events_application_check" CHECK (("founder_commerce_events"."application_status" = 'pending' AND "founder_commerce_events"."applied_at" IS NULL) OR ("founder_commerce_events"."application_status" IN ('applied', 'ignored') AND "founder_commerce_events"."applied_at" IS NOT NULL AND "founder_commerce_events"."last_error_code" IS NULL));
