ALTER TABLE "founder_operator_restorations" DROP CONSTRAINT "founder_operator_restorations_resource_identity_check";--> statement-breakpoint
ALTER TABLE "founder_infrastructure_retirements" ADD COLUMN "retired_runtime_identity" text;--> statement-breakpoint
ALTER TABLE "founder_operator_restorations" ADD COLUMN "old_runtime_identity" text NOT NULL;--> statement-breakpoint
ALTER TABLE "founder_operator_restorations" ADD COLUMN "attempt_count" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "founder_operator_restorations" ADD COLUMN "lease_token" text NOT NULL;--> statement-breakpoint
ALTER TABLE "founder_operator_restorations" ADD COLUMN "lease_expires_at" timestamp with time zone NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "founder_operator_restorations_active_user_idx" ON "founder_operator_restorations" USING btree ("user_id") WHERE "founder_operator_restorations"."status" IN ('in_progress', 'provider_reauthorization_required');--> statement-breakpoint
ALTER TABLE "founder_operator_restorations" ADD CONSTRAINT "founder_operator_restorations_attempt_check" CHECK ("founder_operator_restorations"."attempt_count" > 0);--> statement-breakpoint
ALTER TABLE "founder_operator_restorations" ADD CONSTRAINT "founder_operator_restorations_lease_check" CHECK (length(trim("founder_operator_restorations"."lease_token")) > 0 AND "founder_operator_restorations"."lease_expires_at" >= "founder_operator_restorations"."created_at");--> statement-breakpoint
ALTER TABLE "founder_operator_restorations" ADD CONSTRAINT "founder_operator_restorations_resource_identity_check" CHECK ("founder_operator_restorations"."new_provider_resource_id" IS NULL OR ("founder_operator_restorations"."new_provider_firewall_id" IS NOT NULL AND "founder_operator_restorations"."new_runtime_identity" IS NOT NULL AND "founder_operator_restorations"."new_provider_resource_id" <> "founder_operator_restorations"."old_provider_resource_id" AND "founder_operator_restorations"."new_provider_firewall_id" <> "founder_operator_restorations"."old_provider_firewall_id" AND "founder_operator_restorations"."new_runtime_identity" <> "founder_operator_restorations"."old_runtime_identity"));