ALTER TYPE "public"."founder_product_contract_scenario" ADD VALUE 'initial_general_release_activation' BEFORE 'external_beta_cohort_lifecycle';--> statement-breakpoint
CREATE TABLE "founder_general_release_activations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"operator_id" uuid NOT NULL,
	"runner_id" uuid,
	"status" text DEFAULT 'setup' NOT NULL,
	"service_business_confirmed_at" timestamp with time zone NOT NULL,
	"geography_code" text NOT NULL,
	"admission_state" text NOT NULL,
	"admission_reason" text NOT NULL,
	"published_price_label" text,
	"capacity_observed_at" timestamp with time zone NOT NULL,
	"create_confirmed_at" timestamp with time zone,
	"setup_evidence_digest" text,
	"droplet_created_at" timestamp with time zone,
	"activation_due_at" timestamp with time zone,
	"first_brief_id" uuid,
	"activation_evidence_digest" text,
	"activated_at" timestamp with time zone,
	"entitlement_due_at" timestamp with time zone,
	"work_stopped_at" timestamp with time zone,
	"retirement_due_at" timestamp with time zone,
	"retired_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "founder_general_release_activations_status_check" CHECK (("founder_general_release_activations"."status" IN ('setup', 'waitlisted') AND "founder_general_release_activations"."runner_id" IS NULL AND "founder_general_release_activations"."create_confirmed_at" IS NULL AND "founder_general_release_activations"."setup_evidence_digest" IS NULL AND "founder_general_release_activations"."droplet_created_at" IS NULL AND "founder_general_release_activations"."activated_at" IS NULL AND "founder_general_release_activations"."retirement_due_at" IS NULL AND "founder_general_release_activations"."retired_at" IS NULL) OR ("founder_general_release_activations"."status" = 'provisioning' AND "founder_general_release_activations"."runner_id" IS NULL AND "founder_general_release_activations"."create_confirmed_at" IS NOT NULL AND "founder_general_release_activations"."setup_evidence_digest" ~ '^sha256:[a-f0-9]{64}$' AND "founder_general_release_activations"."droplet_created_at" IS NULL AND "founder_general_release_activations"."activated_at" IS NULL AND "founder_general_release_activations"."retirement_due_at" IS NULL AND "founder_general_release_activations"."retired_at" IS NULL) OR ("founder_general_release_activations"."status" = 'activation_pending' AND "founder_general_release_activations"."runner_id" IS NOT NULL AND "founder_general_release_activations"."create_confirmed_at" IS NOT NULL AND "founder_general_release_activations"."setup_evidence_digest" ~ '^sha256:[a-f0-9]{64}$' AND "founder_general_release_activations"."droplet_created_at" IS NOT NULL AND "founder_general_release_activations"."activated_at" IS NULL AND "founder_general_release_activations"."retirement_due_at" IS NULL AND "founder_general_release_activations"."retired_at" IS NULL) OR ("founder_general_release_activations"."status" = 'activated' AND "founder_general_release_activations"."runner_id" IS NOT NULL AND "founder_general_release_activations"."activated_at" IS NOT NULL AND "founder_general_release_activations"."entitlement_due_at" IS NOT NULL AND "founder_general_release_activations"."retirement_due_at" IS NULL AND "founder_general_release_activations"."retired_at" IS NULL) OR ("founder_general_release_activations"."status" = 'retirement_due' AND "founder_general_release_activations"."runner_id" IS NOT NULL AND "founder_general_release_activations"."work_stopped_at" IS NOT NULL AND "founder_general_release_activations"."retirement_due_at" IS NOT NULL AND "founder_general_release_activations"."retired_at" IS NULL) OR ("founder_general_release_activations"."status" = 'retired' AND "founder_general_release_activations"."runner_id" IS NOT NULL AND "founder_general_release_activations"."work_stopped_at" IS NOT NULL AND "founder_general_release_activations"."retirement_due_at" IS NOT NULL AND "founder_general_release_activations"."retired_at" IS NOT NULL)),
	CONSTRAINT "founder_general_release_activations_admission_check" CHECK ("founder_general_release_activations"."admission_state" IN ('eligible', 'waitlisted', 'unavailable') AND length(trim("founder_general_release_activations"."admission_reason")) BETWEEN 1 AND 500 AND ("founder_general_release_activations"."admission_state" <> 'eligible' OR length(trim("founder_general_release_activations"."published_price_label")) BETWEEN 1 AND 80)),
	CONSTRAINT "founder_general_release_activations_geography_check" CHECK ("founder_general_release_activations"."geography_code" ~ '^[A-Z]{2}$'),
	CONSTRAINT "founder_general_release_activations_creation_check" CHECK (("founder_general_release_activations"."runner_id" IS NULL AND "founder_general_release_activations"."droplet_created_at" IS NULL AND "founder_general_release_activations"."activation_due_at" IS NULL) OR ("founder_general_release_activations"."runner_id" IS NOT NULL AND "founder_general_release_activations"."create_confirmed_at" IS NOT NULL AND "founder_general_release_activations"."droplet_created_at" IS NOT NULL AND "founder_general_release_activations"."activation_due_at" = "founder_general_release_activations"."droplet_created_at" + interval '24 hours')),
	CONSTRAINT "founder_general_release_activations_activation_check" CHECK (("founder_general_release_activations"."activated_at" IS NULL AND "founder_general_release_activations"."first_brief_id" IS NULL AND "founder_general_release_activations"."activation_evidence_digest" IS NULL AND "founder_general_release_activations"."entitlement_due_at" IS NULL) OR ("founder_general_release_activations"."activated_at" IS NOT NULL AND "founder_general_release_activations"."first_brief_id" IS NOT NULL AND "founder_general_release_activations"."activation_evidence_digest" ~ '^sha256:[a-f0-9]{64}$' AND "founder_general_release_activations"."droplet_created_at" IS NOT NULL AND "founder_general_release_activations"."activated_at" >= "founder_general_release_activations"."droplet_created_at" AND "founder_general_release_activations"."activation_due_at" IS NOT NULL AND "founder_general_release_activations"."activated_at" <= "founder_general_release_activations"."activation_due_at" AND "founder_general_release_activations"."entitlement_due_at" = "founder_general_release_activations"."activated_at" + interval '24 hours')),
	CONSTRAINT "founder_general_release_activations_retirement_check" CHECK (("founder_general_release_activations"."retirement_due_at" IS NULL AND "founder_general_release_activations"."retired_at" IS NULL) OR ("founder_general_release_activations"."retirement_due_at" IS NOT NULL AND "founder_general_release_activations"."work_stopped_at" IS NOT NULL AND ("founder_general_release_activations"."retired_at" IS NULL OR "founder_general_release_activations"."retired_at" >= "founder_general_release_activations"."work_stopped_at")))
);
--> statement-breakpoint
ALTER TABLE "founder_general_release_activations" ADD CONSTRAINT "founder_general_release_activations_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "founder_general_release_activations" ADD CONSTRAINT "founder_general_release_activations_operator_id_operators_id_fk" FOREIGN KEY ("operator_id") REFERENCES "public"."operators"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "founder_general_release_activations" ADD CONSTRAINT "founder_general_release_activations_runner_id_runners_id_fk" FOREIGN KEY ("runner_id") REFERENCES "public"."runners"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "founder_general_release_activations" ADD CONSTRAINT "founder_general_release_activations_first_brief_id_operator_morning_briefs_id_fk" FOREIGN KEY ("first_brief_id") REFERENCES "public"."operator_morning_briefs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "founder_general_release_activations_user_idx" ON "founder_general_release_activations" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "founder_general_release_activations_operator_idx" ON "founder_general_release_activations" USING btree ("operator_id");--> statement-breakpoint
CREATE UNIQUE INDEX "founder_general_release_activations_runner_idx" ON "founder_general_release_activations" USING btree ("runner_id") WHERE "founder_general_release_activations"."runner_id" IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "founder_general_release_activations_brief_idx" ON "founder_general_release_activations" USING btree ("first_brief_id") WHERE "founder_general_release_activations"."first_brief_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "founder_general_release_activations_deadline_idx" ON "founder_general_release_activations" USING btree ("status","activation_due_at","entitlement_due_at","retirement_due_at");