ALTER TABLE "founder_release_decisions" ALTER COLUMN "user_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "founder_release_decisions" ALTER COLUMN "operator_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "founder_general_release_activations" ADD COLUMN "release_decision_id" uuid;--> statement-breakpoint
ALTER TABLE "founder_release_decisions" ADD COLUMN "authority_expires_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "founder_general_release_activations" ADD CONSTRAINT "founder_general_release_activations_release_decision_id_founder_release_decisions_id_fk" FOREIGN KEY ("release_decision_id") REFERENCES "public"."founder_release_decisions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "founder_release_decisions_global_candidate_idx" ON "founder_release_decisions" USING btree ("stage","application_revision","runtime_revision","decided_at") WHERE "founder_release_decisions"."stage" = 'initial_general_release';--> statement-breakpoint
ALTER TABLE "founder_release_decisions" ADD CONSTRAINT "founder_release_decisions_scope_check" CHECK (("founder_release_decisions"."stage" = 'initial_general_release' AND "founder_release_decisions"."user_id" IS NULL AND "founder_release_decisions"."operator_id" IS NULL) OR ("founder_release_decisions"."stage" <> 'initial_general_release' AND "founder_release_decisions"."user_id" IS NOT NULL AND "founder_release_decisions"."operator_id" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "founder_release_decisions" ADD CONSTRAINT "founder_release_decisions_initial_general_release_manifest_check" CHECK ("founder_release_decisions"."stage" <> 'initial_general_release' OR (jsonb_array_length("founder_release_decisions"."capability_manifest") = 5 AND "founder_release_decisions"."capability_manifest" @> '["openai", "anthropic", "calendar_reading", "gmail_reading", "gmail_sending"]'::jsonb));--> statement-breakpoint
ALTER TABLE "founder_release_decisions" ADD CONSTRAINT "founder_release_decisions_initial_general_release_expiry_check" CHECK ("founder_release_decisions"."stage" <> 'initial_general_release' OR "founder_release_decisions"."outcome" = 'deny' OR "founder_release_decisions"."authority_expires_at" IS NOT NULL);--> statement-breakpoint
ALTER TABLE "founder_release_decisions" ADD CONSTRAINT "founder_release_decisions_initial_general_release_evidence_set_check" CHECK ("founder_release_decisions"."stage" <> 'initial_general_release' OR "founder_release_decisions"."outcome" = 'deny' OR ("founder_release_decisions"."outcome" IN ('enter', 'resume') AND jsonb_array_length("founder_release_decisions"."evidence_digests") = 12) OR ("founder_release_decisions"."outcome" = 'hold' AND jsonb_array_length("founder_release_decisions"."evidence_digests") >= 13));--> statement-breakpoint
ALTER TABLE "founder_release_decisions" ADD CONSTRAINT "founder_release_decisions_evidence_digests_check" CHECK (jsonb_array_length("founder_release_decisions"."evidence_digests") > 0 AND jsonb_path_query_array("founder_release_decisions"."evidence_digests", '$[*] ? (!(@ like_regex "^sha256:[a-f0-9]{64}$"))') = '[]'::jsonb);
