import { isValidAgentId } from "@/src/server/agents/agent-id";
import {
  AgentSecretKeyringError,
  AgentSecretPersistenceError,
  generateApiServerKeyForUser,
  isAgentSecretKind,
  isUserManagedAgentSecretKind,
  listAgentSecretStatusesForUser,
  replaceAgentSecretForUser,
  revokeAgentSecretForUser,
} from "@/src/server/agents/agent-secrets";
import {
  type ConfiguredApplicationUserResolution,
  requireConfiguredApplicationUser,
} from "@/src/server/users/configured-application-user";

type AgentSecretsRouteContext = {
  params: Promise<{
    agentId?: string;
  }>;
};

type AgentSecretsRouteDependencies = {
  requireApplicationUser?: typeof requireConfiguredApplicationUser;
};

type SecretMutationPayload = {
  kind?: unknown;
  value?: unknown;
  generate?: unknown;
};

export const dynamic = "force-dynamic";

export async function GET(
  _request: Request,
  context: AgentSecretsRouteContext,
  dependencies: AgentSecretsRouteDependencies = {},
) {
  const decodedAgentId = await decodeAgentId(context);

  if (!decodedAgentId.ok) {
    return validationResponse("Agent ID must be a valid UUID.");
  }

  const applicationUser = await (
    dependencies.requireApplicationUser ?? requireConfiguredApplicationUser
  )();

  if (!applicationUser.ok) {
    return authenticationResponse(applicationUser);
  }

  try {
    const result = await listAgentSecretStatusesForUser(
      applicationUser.userId,
      decodedAgentId.agentId,
    );

    if (result.ok) {
      return Response.json(result);
    }

    if (result.reason === "agent_not_found") {
      return notFoundResponse();
    }

    return validationResponse("Agent ID must be a valid UUID.");
  } catch (error) {
    if (error instanceof AgentSecretPersistenceError) {
      return persistenceErrorResponse();
    }

    throw error;
  }
}

export async function PUT(
  request: Request,
  context: AgentSecretsRouteContext,
  dependencies: AgentSecretsRouteDependencies = {},
) {
  const decodedAgentId = await decodeAgentId(context);

  if (!decodedAgentId.ok) {
    return validationResponse("Agent ID must be a valid UUID.");
  }

  const payload = await readMutationPayload(request);

  if (!payload.ok) {
    return validationIssuesResponse(payload.issues);
  }

  if (!isAgentSecretKind(payload.value.kind)) {
    return validationIssuesResponse([{ field: "kind", message: "Secret kind is not supported." }]);
  }

  if (payload.value.kind === "api_server_key") {
    if (payload.value.generate !== true) {
      return validationIssuesResponse([
        { field: "generate", message: "api_server_key must be generated by the server." },
      ]);
    }
  } else if (!isUserManagedAgentSecretKind(payload.value.kind)) {
    return validationIssuesResponse([{ field: "kind", message: "Secret kind is not writable." }]);
  }

  const applicationUser = await (
    dependencies.requireApplicationUser ?? requireConfiguredApplicationUser
  )();

  if (!applicationUser.ok) {
    return authenticationResponse(applicationUser);
  }

  try {
    const result =
      payload.value.kind === "api_server_key"
        ? await generateApiServerKeyForUser(applicationUser.userId, decodedAgentId.agentId)
        : await replaceAgentSecretForUser(applicationUser.userId, decodedAgentId.agentId, {
            kind: payload.value.kind,
            value: payload.value.value,
          });

    return mutationResponse(result);
  } catch (error) {
    if (error instanceof AgentSecretKeyringError) {
      return secretConfigurationErrorResponse();
    }

    if (error instanceof AgentSecretPersistenceError) {
      return persistenceErrorResponse();
    }

    throw error;
  }
}

export async function DELETE(
  request: Request,
  context: AgentSecretsRouteContext,
  dependencies: AgentSecretsRouteDependencies = {},
) {
  const decodedAgentId = await decodeAgentId(context);

  if (!decodedAgentId.ok) {
    return validationResponse("Agent ID must be a valid UUID.");
  }

  const payload = await readMutationPayload(request);

  if (!payload.ok) {
    return validationIssuesResponse(payload.issues);
  }

  if (!isAgentSecretKind(payload.value.kind)) {
    return validationIssuesResponse([{ field: "kind", message: "Secret kind is not supported." }]);
  }

  const applicationUser = await (
    dependencies.requireApplicationUser ?? requireConfiguredApplicationUser
  )();

  if (!applicationUser.ok) {
    return authenticationResponse(applicationUser);
  }

  try {
    const result = await revokeAgentSecretForUser(applicationUser.userId, decodedAgentId.agentId, {
      kind: payload.value.kind,
    });

    return mutationResponse(result);
  } catch (error) {
    if (error instanceof AgentSecretPersistenceError) {
      return persistenceErrorResponse();
    }

    throw error;
  }
}

async function readMutationPayload(request: Request): Promise<
  | {
      ok: true;
      value: SecretMutationPayload;
    }
  | {
      ok: false;
      issues: Array<{ field: string; message: string }>;
    }
> {
  let payload: unknown;

  try {
    payload = await request.json();
  } catch {
    return {
      ok: false,
      issues: [{ field: "body", message: "Request body must be valid JSON." }],
    };
  }

  if (!isRecord(payload)) {
    return {
      ok: false,
      issues: [{ field: "body", message: "Request body must be an object." }],
    };
  }

  return { ok: true, value: payload };
}

function mutationResponse(
  result: Awaited<ReturnType<typeof replaceAgentSecretForUser | typeof revokeAgentSecretForUser>>,
) {
  if (result.ok) {
    return Response.json(result);
  }

  if (result.reason === "agent_not_found") {
    return notFoundResponse();
  }

  if (result.reason === "validation_failed") {
    return validationIssuesResponse(
      result.issues ?? [{ field: "value", message: "Secret value is invalid." }],
    );
  }

  return validationResponse("Agent ID must be a valid UUID.");
}

function authenticationResponse(
  result: Exclude<ConfiguredApplicationUserResolution, { ok: true }>,
) {
  return Response.json(
    {
      error: {
        code: result.code,
        message:
          result.status === 401
            ? "Authentication is required."
            : "Authentication is not configured safely.",
      },
    },
    { status: result.status },
  );
}

async function decodeAgentId(context: AgentSecretsRouteContext): Promise<
  | {
      ok: true;
      agentId: string;
    }
  | {
      ok: false;
    }
> {
  const params = await context.params;
  let decodedAgentId: string;

  try {
    decodedAgentId = decodeURIComponent(params.agentId ?? "").trim();
  } catch (error) {
    if (error instanceof URIError) {
      return { ok: false };
    }

    throw error;
  }

  if (!isValidAgentId(decodedAgentId)) {
    return { ok: false };
  }

  return { ok: true, agentId: decodedAgentId };
}

function validationResponse(message: string) {
  return Response.json(
    {
      error: {
        code: "validation_failed",
        message,
      },
    },
    { status: 400 },
  );
}

function validationIssuesResponse(issues: Array<{ field: string; message: string }>) {
  return Response.json(
    {
      error: {
        code: "validation_failed",
        message: "Request validation failed.",
        issues,
      },
    },
    { status: 400 },
  );
}

function notFoundResponse() {
  return Response.json(
    {
      error: {
        code: "agent_not_found",
        message: "Agent could not be found.",
      },
    },
    { status: 404 },
  );
}

function secretConfigurationErrorResponse() {
  return Response.json(
    {
      error: {
        code: "agent_secret_configuration_invalid",
        message: "Agent secret storage is not configured safely.",
      },
    },
    { status: 503 },
  );
}

function persistenceErrorResponse() {
  return Response.json(
    {
      error: {
        code: "agent_secret_update_failed",
        message: "Agent secret storage could not be updated.",
      },
    },
    { status: 500 },
  );
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
